templates:
  new_patient_welcome:
    subject: "Welcome to DentaMind - {patient_name}"
    body: |
      Dear {patient_name},

      Welcome to DentaMind! We're excited to have you as our patient. Your first appointment is scheduled for {appointment_date} at {appointment_time}.

      Before your visit, please:
      1. Complete your patient forms online at {patient_portal_url}
      2. Bring your insurance card and ID
      3. Arrive 15 minutes early

      If you have any questions, feel free to call us at {office_phone} or reply to this email.

      Best regards,
      {doctor_name}
      DentaMind Dental Care

  appointment_confirmation:
    subject: "Appointment Confirmation - {patient_name}"
    body: |
      Hi {patient_name},

      This is a confirmation of your appointment on {date} at {time} with Dr. {doctor_name}.
      Appointment Type: {appointment_type}
      Duration: {duration} minutes

      Please:
      - Arrive 10 minutes early
      - Bring your insurance card if it's changed
      - Complete any pending forms at {patient_portal_url}

      To reschedule or cancel, please call {office_phone} at least 24 hours in advance.

      Best regards,
      DentaMind Team

  missed_appointment:
    subject: "We Missed You - {patient_name}"
    body: |
      Dear {patient_name},

      We noticed you missed your appointment scheduled for {date} at {time}.
      We understand things come up, and we'd like to help you reschedule.

      Please call us at {office_phone} or click here to schedule online: {scheduling_url}

      Your oral health is important to us, and we want to ensure you receive the care you need.

      Best regards,
      {doctor_name}
      DentaMind Dental Care

  financial_agreement:
    subject: "Financial Agreement - {patient_name}"
    body: |
      Dear {patient_name},

      Thank you for choosing DentaMind for your dental care. Please find attached your financial agreement for the proposed treatment plan.

      Treatment Plan Summary:
      - Total Cost: ${total_cost}
      - Insurance Coverage: ${insurance_coverage}
      - Patient Portion: ${patient_portion}
      - Payment Options: {payment_options}

      Please review and sign the attached agreement. You can:
      1. Sign electronically through our portal: {portal_url}
      2. Print, sign, and bring to your next appointment
      3. Call us with any questions: {office_phone}

      Best regards,
      DentaMind Billing Department

  insurance_documentation:
    subject: "Insurance Documentation Request - {patient_name}"
    body: |
      Dear {patient_name},

      We need additional documentation for your insurance claim. Please provide:
      - Updated insurance card (front and back)
      - Any recent insurance changes
      - Referral forms if required

      You can upload these documents through our secure portal: {portal_url}

      If you have any questions, please contact our insurance department at {insurance_phone}.

      Best regards,
      DentaMind Insurance Team

  lab_case_update:
    subject: "Lab Case Update - {patient_name}"
    body: |
      Dear {patient_name},

      Your dental lab case has been updated:

      Case Details:
      - Case Number: {case_number}
      - Type: {case_type}
      - Status: {status}
      - Expected Completion: {completion_date}

      Next Steps:
      1. We will contact you when your case is ready
      2. Schedule your fitting appointment
      3. Bring your insurance card to the fitting

      Questions? Call us at {office_phone}

      Best regards,
      DentaMind Lab Team

  treatment_plan:
    subject: "Your Treatment Plan - {patient_name}"
    body: |
      Dear {patient_name},

      Thank you for your recent visit. Please find attached your comprehensive treatment plan.

      Plan Highlights:
      - Recommended Procedures: {procedures}
      - Estimated Timeline: {timeline}
      - Total Investment: ${total_cost}
      - Insurance Coverage: ${insurance_coverage}

      Next Steps:
      1. Review the attached treatment plan
      2. Schedule your next appointment
      3. Contact us with any questions

      To schedule, call {office_phone} or visit: {scheduling_url}

      Best regards,
      {doctor_name}
      DentaMind Dental Care

  recall_reminder:
    subject: "Time for Your Checkup - {patient_name}"
    body: |
      Dear {patient_name},

      It's time for your regular dental checkup! We recommend visiting every 6 months to maintain optimal oral health.

      Available Appointment Times:
      {available_times}

      Please schedule your appointment:
      - Online: {scheduling_url}
      - By Phone: {office_phone}

      Don't forget to bring your insurance card if it's changed since your last visit.

      Best regards,
      DentaMind Team

  payment_reminder:
    subject: "Payment Reminder - {patient_name}"
    body: |
      Dear {patient_name},

      This is a friendly reminder about your outstanding balance:

      Amount Due: ${amount_due}
      Due Date: {due_date}

      Payment Options:
      1. Pay online: {payment_portal_url}
      2. Call us: {office_phone}
      3. Mail a check to: {office_address}

      If you have any questions about your bill, please contact our billing department.

      Best regards,
      DentaMind Billing Team

  emergency_instructions:
    subject: "Emergency Dental Care Instructions - {patient_name}"
    body: |
      Dear {patient_name},

      Thank you for contacting us about your dental emergency. Here are the next steps:

      Emergency Instructions:
      1. {emergency_instructions}
      2. Take {medication_instructions} if needed
      3. Apply {first_aid_instructions}

      Please call our emergency line at {emergency_phone} if:
      - Pain worsens
      - Swelling increases
      - You have difficulty breathing

      We're here to help 24/7 for dental emergencies.

      Best regards,
      DentaMind Emergency Team 